### ISSUE TITLE
Crash on start - Microsoft Edge can't read and write to it's home directory

### ISSUE THREAD

**Issue by tctcs-xevus** [xenesty/AkashaScanner#14]
Win 10, Edge 110.0.1587.5

When I start the app, first it says "Microsoft Edge can't read and write to it's home directory" and then crashes with below trace

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
>    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
>    at Microsoft.Web.WebView2.WinForms.WebView2.InitCoreWebView2Async(CoreWebView2Environment environment)
>    at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
>    at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.InvokeAsync(Func`1 workItem)
>    at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.<>c.<.cctor>b__8_0(Exception exception)
> 
> 
> ************** Loaded Assemblies **************
> System.Private.CoreLib
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> AkashaScanner
>     Assembly Version: 0.4.1.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Windows.Forms.Primitives
>     Assembly Version: 6.0.2.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 6.0.2.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.ComponentModel.Primitives
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime.InteropServices
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Drawing.Primitives
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Collections.Specialized
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Web.WebView2.Core
>     Assembly Version: 1.0.1210.39
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Threading
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Diagnostics.TraceSource
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Collections
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Drawing.Common
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.AspNetCore.Components.WebView.WindowsForms
>     Assembly Version: 1.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.AspNetCore.Components
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Win32.Primitives
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.ComponentModel.EventBasedAsync
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Threading.Thread
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.ComponentModel.TypeConverter
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.AspNetCore.Components.Web
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.ObjectModel
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Web.WebView2.WinForms
>     Assembly Version: 1.0.1210.39
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.ComponentModel
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Memory
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Numerics.Vectors
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Resources.Extensions
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Drawing
>     Assembly Version: 6.0.2.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Linq
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Win32.SystemEvents
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Logging
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.DependencyInjection.Abstractions
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Hosting
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Hosting.Abstractions
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Configuration.Abstractions
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.DependencyInjection
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.FileProviders.Abstractions
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.FileProviders.Physical
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Primitives
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Diagnostics.DiagnosticSource
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Diagnostics.Tracing
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Configuration
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime.InteropServices.RuntimeInformation
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Configuration.EnvironmentVariables
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Configuration.FileExtensions
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Configuration.Binder
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Configuration.Json
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.IO.FileSystem.Watcher
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Collections.Concurrent
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.FileSystemGlobbing
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Threading.Overlapped
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Text.Json
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Text.Encoding.Extensions
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime.CompilerServices.Unsafe
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Options
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Logging.Abstractions
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Logging.EventLog
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Logging.Configuration
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Options.ConfigurationExtensions
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Logging.Console
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Logging.Debug
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.Logging.EventSource
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Serilog.Extensions.Logging.File
>     Assembly Version: 3.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Serilog
>     Assembly Version: 2.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> netstandard
>     Assembly Version: 2.1.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Serilog.Formatting.Compact
>     Assembly Version: 1.1.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Serilog.Sinks.Async
>     Assembly Version: 1.5.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Serilog.Sinks.RollingFile
>     Assembly Version: 2.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Serilog.Sinks.File
>     Assembly Version: 2.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Text.RegularExpressions
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime.Extensions
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Threading.Timer
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Private.Uri
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Serilog.Extensions.Logging
>     Assembly Version: 2.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> OpenCvSharp
>     Assembly Version: 1.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.AspNetCore.Components.WebView
>     Assembly Version: 6.0.8.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.JSInterop
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Console
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Diagnostics.EventLog
>     Assembly Version: 7.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> Microsoft.Extensions.FileProviders.Composite
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Threading.ThreadPool
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Threading.Tasks
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Runtime.Loader
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Collections.NonGeneric
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Diagnostics.StackTrace
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Reflection.Metadata
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> System.Collections.Immutable
>     Assembly Version: 6.0.0.0
>     Win32 Version: n/a
>     CodeBase: 
> ----------------------------------------
> 
> ************** JIT Debugging **************
> 
> 
>

**Comment by xenesty** [comment]
Sorry for the late reply. Been busy these days.

Can you try manually installing [Microsoft Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) on your device?

**Comment by tctcs-xevus** [comment]
Installation falied. The Microsoft Edge WebView2 Runtime is already installted for the system.
