### ISSUE TITLE
Error exporting data to GOOD format

### ISSUE THREAD

**Issue by evearellie** [xenesty/AkashaScanner#22]
The program scanned my artifacts, characters, and weapons perfectly, but now it's giving me a very weird error that prevents the program from working when I try and export, and I don't know how to fix it.

When I hit "export" on the GOOD format tab, it gives me this popup:
![image](https://user-images.githubusercontent.com/130886653/232272147-4ffeae32-b620-414d-aa06-e3c67c642b9b.png)

this is the relevant text under the details I think?
"See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key 'Invalid' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AkashaScanner.Core.Exporters.GoodExporter.Export(String& output, IDataFile`1 weaponFile, IDataFile`1 artifactFile, IDataFile`1 characterFile) in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Core\Exporters\GoodExporter.cs:line 110
   at AkashaScanner.Ui.Pages.Exports.GoodExports.HandleSubmit()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass9_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.<>c.<.cctor>b__8_0(Exception exception)"

I've tried like 5 times now, restarted my laptop. closed an reopened the program multiple times, but nothing works.

**Comment by xenesty** [comment]
Oops, that's my bad. It means that there are one or more artifact cannot be identified and stored as "Invalid" artifacts. Maybe you can open the artifact json files under "ScannedData" to manually edit those invalid artifacts out? Will fix this ASAP so that it will show a warning instead of crashes.

**Comment by Lkkenji** [comment]
I don't know if its only for me, but apperently The scanner gives "Invalid" to all Hp percent main stat, hope it helps!

**Comment by acefalobi** [comment]
I was getting this so I cloned and debugged the code and found out that using Windows Auto SDR makes the image from `Graphics.CopyFromScreen` look blown out (see screenshots) and hard for the OCR to get the correct text especially for main stats.

So you can also check to see if you have Auto SDR on.

Bitmap with Auto SDR on
![image](https://github.com/xenesty/AkashaScanner/assets/10771222/b729da2a-dbcf-48f1-8c78-cc2cb8d89cf3)


Bitmap without Auto SDR on
![image](https://github.com/xenesty/AkashaScanner/assets/10771222/fc190136-e4c9-4ee1-b7c3-166a255200c9)
