### ISSUE TITLE
Character manifest cannot be downloaded

### ISSUE THREAD

**Issue by floravsolomon** [xenesty/AkashaScanner#44]
Character manifest cannot be downloaded on Genshin 4.4 from any scanner screen (Characters, Artifacts, nor Weapons). Other two manifests seem to be downloading appropriately. 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AkashaScanner.Core.DataCollections.Repositories.CharactersHoYoWikiRepository.Load() in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Core\DataCollections\Repositories\CharactersHoYoWikiRepository.cs:line 127
   at AkashaScanner.Core.DataCollections.BaseCollection`1.LoadRemote() in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Core\DataCollections\BaseCollection.cs:line 72
   at AkashaScanner.Ui.Partials.DataUpdate.OnUpdate() in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Ui\Partials\DataUpdate.razor:line 66
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass9_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.<>c.<.cctor>b__8_0(Exception exception)
```

Logs:
[akashascanner-20240205173525-20240205.txt](https://github.com/xenesty/AkashaScanner/files/14172605/akashascanner-20240205173525-20240205.txt)

**Comment by akrios-d** [comment]
Hi, I did a fix for it in my fork, mind check and validate if it is still happening?

**Comment by Wittich04** [comment]
Hello! I used your fork @akrios-d and it works for me! (I just hope It didnt come with any viruses)

**Comment by akrios-d** [comment]
If you prefer, you can also build. Any issues, let me know
