### ISSUE TITLE
Artifact Scanner Won't Start

### ISSUE THREAD

**Issue by PirateKing555** [xenesty/AkashaScanner#50]
**Describe the bug**
There is a new feature on the Artifact page that has an option to auto-lock artifacts, and it's causing the Scanner to crash

**To Reproduce**
Just scan as usual
Characters and Weapons still work, this issue is with Artifacts specifically

**Expected behavior**
I expect it to scan, not crash

**Error Code**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: Cannot get item count
   at AkashaScanner.Core.Scappers.EquipableScrapper`3.GetItemCount() in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Core\Scrappers\EquipableScrapper.cs:line 126
   at AkashaScanner.Core.Scappers.EquipableScrapper`3.Run(TaskQueue tasks, C config) in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Core\Scrappers\EquipableScrapper.cs:line 32
   at AkashaScanner.Core.Scappers.EquipableScrapper`3.Execute(C config) in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Core\Scrappers\EquipableScrapper.cs:line 101
   at AkashaScanner.Core.Scappers.BaseScrapper`2.Start(C config) in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Core\Scrappers\BaseScrapper.cs:line 100
   at AkashaScanner.Ui.Pages.Scanners.ArtifactScanner.HandleSubmit() in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Ui\Pages\Scanners\ArtifactScanner.razor:line 74
   at AkashaScanner.Ui.Partials.Scanner.<HandleSubmit>b__42_0() in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Ui\Partials\Scanner.razor:line 122
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AkashaScanner.Ui.Partials.Scanner.HandleSubmit() in C:\Users\Kith\workspace\AkashaScanner\AkashaScanner\Ui\Partials\Scanner.razor:line 120
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass9_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.<>c.<.cctor>b__8_0(Exception exception)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
AkashaScanner
    Assembly Version: 0.4.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1210.39
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components.WebView.WindowsForms
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components.Web
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1210.39
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Hosting
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.EventLog
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Console
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.EventSource
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Serilog.Extensions.Logging.File
    Assembly Version: 3.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Serilog.Formatting.Compact
    Assembly Version: 1.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Serilog.Sinks.Async
    Assembly Version: 1.5.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Serilog.Sinks.RollingFile
    Assembly Version: 2.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 2.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Timer
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Serilog.Extensions.Logging
    Assembly Version: 2.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
OpenCvSharp
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components.WebView
    Assembly Version: 6.0.8.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.JSInterop
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.EventLog
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileProviders.Composite
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Tasks
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileProviders.Embedded
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Xml.XDocument
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Users/Rick/Downloads/AkashaScanner-v0.4.2/System.Private.CoreLib.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components.Forms
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Tesseract
    Assembly Version: 4.1.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WindowsInput
    Assembly Version: 1.0.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.FileSystem
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Globalization
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.FileSystem.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
InteropRuntimeImplementer.LeptonicaApiSignaturesInstance
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Users/Rick/Downloads/AkashaScanner-v0.4.2/Tesseract.dll
----------------------------------------
InteropRuntimeImplementer.TessApiSignaturesInstance
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Users/Rick/Downloads/AkashaScanner-v0.4.2/Tesseract.dll
----------------------------------------
FuzzySharp
    Assembly Version: 1.0.4.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------

************** JIT Debugging **************

**Comment by akrios-d** [comment]
hi please take a look at my fork, https://github.com/akrios-d/AkashaScanner if the still happen open an issue and i'll take a better look

**Comment by PirateKing555** [comment]
> hi please take a look at my fork, https://github.com/akrios-d/AkashaScanner if the still happen open an issue and i'll take a better look

That fixed the issue, thank you!
